version: '3'
services:
  db:
    image: postgres:14.2-alpine
    container_name: myapp-postgres-14.2
    volumes:
      - postgres_data:/var/lib/postgresql/data
    command: "postgres -c 'max_connections=500'"
    environment:
      POSTGRES_DB: myappdb
      POSTGRES_USER: my_user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
  myrailsapp:

    build: .
    command: "bundle exec rails s -p 3000 -b '0.0.0.0'"
    environment:
      DB_HOST: db
      DB_NAME: myappdb
      DB_USERNAME: my_user
      DB_PASSWORD: password
    volumes:
      - .:/app:cached
    ports:
      - "3000:3000"
      - "3001:3001"
    depends_on:
      - db
volumes:
  postgres_data: {}
networks:
  default:
    name: myapp_default

